### ISSUE TITLE
PSR Log dependency update

### ISSUE THREAD

**Issue by neradp** [markrogoyski/simplelog-php#1]
Please update composer dependency "psr/log": "1.0.*", to the newest version

**Comment by markrogoyski** [comment]
Thanks for the info. I'll look into what is new in version 1.1 and update it shortly.

**Comment by markrogoyski** [comment]
The psr/log dependency has been updated to the latest version in [v.0.4.0](https://github.com/markrogoyski/simplelog-php/releases/tag/v0.4.0). Thanks
